name: bike_service
description: 重機保養GPS軌跡App
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  firebase_core: ^3.4.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.3.0
  geolocator: ^13.0.1
  latlong2: ^0.9.1
  flutter_map: ^7.0.2
  csv: ^6.0.0
  path_provider: ^2.1.4
  image_picker: ^1.1.2
  flutter_local_notifications: ^17.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
    
